import type{FieldDef,Rule,RuleGroup,RuleOp,ScreenState}from'./filterEngine'

const number=(id:string,label:string,group:string,defaultOp:RuleOp='>=',placeholder?:string):FieldDef=>({id,label,kind:'number',defaultOp,placeholder,group})
const text=(id:string,label:string,group:string,defaultOp:RuleOp='='):FieldDef=>({id,label,kind:'text',defaultOp,group})
const bool=(id:string,label:string,group:string,defaultOp:RuleOp='true'):FieldDef=>({id,label,kind:'boolean',defaultOp,group})

// Curated registry from the original Bottom Fishing screener. Source names stay
// snake_case so the UI reads the immutable sidecar without recreating detectors.
export const bottomFieldDefs:FieldDef[]=[
  text('ticker','Ticker','Core','contains'),number('score','Bottom score','Core'),number('focusBlend','Focus blend','Core'),number('price','Price','Core'),
  text('actionability','Actionability','Core'),text('primary_setup','Primary setup','Core'),text('sector','Sector','Core','contains'),text('industry','Industry','Core','contains'),text('data_status','Data status','Core'),
  text('trade_status','Trade status','Trade readiness'),text('trigger_state','Trigger state','Trade readiness'),number('entry_risk_pct','Structural risk %','Trade readiness','<='),number('extension_atr','Extension (ATR)','Trade readiness','<='),number('distance_to_trigger_pct','Distance to trigger %','Trade readiness','between','-5,1.5'),number('distance_to_trigger_atr','Distance to trigger (ATR)','Trade readiness','between','-1,1'),text('risk_level','Risk level','Trade readiness'),
  number('rs_rating','RS rating (1–99)','Relative strength'),number('rs_score_weighted','RS weighted','Relative strength'),number('rs_score_6m','RS 6M %','Relative strength'),number('rs_score_3m','RS 3M %','Relative strength'),number('mansfield_rs','Mansfield RS','Relative strength'),number('rs_line_52w_distance_pct','RS-line distance to high %','Relative strength'),bool('rs_line_at_52w_high','RS-line at 52W high','Relative strength'),bool('rs_new_high_before_price','RS new high before price','Relative strength'),bool('rs_turning_up','RS turning up','Relative strength'),number('distance_to_52w_high_pct','Distance to 52W high %','Relative strength'),
  number('base_quality_score','Base quality','Setup & base'),number('base_length_bars','Base length (bars)','Setup & base'),number('base_depth_pct','Base depth %','Setup & base','<='),number('sma_compression_pct','SMA compression %','Setup & base','<='),number('base_age_weeks','Base age (weeks)','Setup & base'),number('accumulation_score','Accumulation score','Setup & base'),number('institutional_footprint_score','Institutional footprint','Setup & base'),number('crash_base_score','Crash-base score','Setup & base'),number('ema_stack_launch_score','EMA-stack launch score','Setup & base'),text('ema_stack_phase','EMA-stack phase','Setup & base'),number('rwb_squeeze_score','RWB squeeze score','Setup & base'),text('rwb_squeeze_phase','RWB squeeze phase','Setup & base'),number('long_base_score','Long-base score','Setup & base'),text('long_base_phase','Long-base phase','Setup & base'),number('ma_cluster_score','MA-cluster score','Setup & base'),text('ma_cluster_phase','MA-cluster phase','Setup & base'),text('special_alert_level','Special detector alert','Setup & base'),bool('trendline_breakout_5y','5Y trendline breakout','Setup & base'),
  number('up_down_vol_ratio_50d','Up/down volume 50D','Volume & demand'),number('demand_supply_ratio','Demand/supply','Volume & demand'),number('support_volume_events','Support-volume events','Volume & demand'),number('volume_ratio_50d','Volume ratio 50D','Volume & demand'),number('weekly_breakout_rvol','Weekly breakout RVOL','Volume & demand'),number('rvol_today','RVOL today','Volume & demand'),bool('pocket_pivot','Pocket pivot','Volume & demand'),bool('dryup_after_accumulation','Dry-up after accumulation','Volume & demand'),bool('daily_rvol_headsup','Daily RVOL heads-up','Volume & demand'),
  number('adr_pct','ADR % (20D)','Momentum & volatility'),number('ret_1d_pct','Return 1D %','Momentum & volatility'),number('ret_1m_pct','Return 1M %','Momentum & volatility'),number('ret_3m_pct','Return 3M %','Momentum & volatility'),number('ret_6m_pct','Return 6M %','Momentum & volatility'),number('avg_dollar_volume_50d','Average $ volume 50D','Momentum & volatility'),
  number('weinstein_stage','Weinstein stage','Stage analysis','='),text('weinstein_substage','Weinstein substage','Stage analysis'),number('weinstein_stage_quality_score','Stage fit (not ranking)','Stage analysis'),text('weinstein_stage_origin','Stage origin','Stage analysis'),number('weinstein_ext_pct','Distance vs 30W SMA %','Stage analysis','<='),number('weekly_30w_slope_pct','30W slope %','Stage analysis'),number('weinstein_range_104w_pos','104W range position','Stage analysis'),number('weinstein_range_156w_pos','156W range position','Stage analysis'),number('weinstein_range_260w_pos','260W range position','Stage analysis'),number('weinstein_resistance_zone_high','Stage resistance','Stage analysis'),number('weinstein_support_zone_low','Stage support','Stage analysis'),text('long_term_context','Long-term context','Stage analysis'),number('secular_recovery_score','Recovery score','Stage analysis'),bool('near_secular_resistance','Near secular resistance','Stage analysis'),number('long_term_drawdown_pct','Long-term drawdown %','Stage analysis'),
  number('float_shares','Float shares','Float & ownership'),number('short_pct_float','Short % float','Float & ownership'),bool('insider_buying','Insider buying','Float & ownership'),
]

let sequence=0
const rule=(field:string,op:RuleOp,value=''):Rule=>({id:`bottom-rule-${sequence++}`,field,op,value})
const group=(logic:'ALL'|'ANY',rules:Rule[]):RuleGroup=>({id:`bottom-group-${sequence++}`,logic,rules})
const all=(...rules:Rule[])=>group('ALL',rules)
const any=(field:string,values:string[])=>group('ANY',values.map(value=>rule(field,'=',value)))
const screen=(name:string,groups:RuleGroup[],sorting:ScreenState['sorting'],visibility:Record<string,boolean>={}):ScreenState=>({name,rootLogic:'ALL',groups,sorting,visibility,recipe:'All',query:'',pageSize:100})

// Exact 19 built-ins from the original savedScreens.ts. Set membership becomes
// an ANY group while the screen root remains ALL.
export const bottomBuiltInScreens:ScreenState[]=[
  screen('Actionable Tight Bases',[any('actionability',['actionable_now','near_actionable','forming']),any('primary_setup',['tight_breakout','minervini','glb','long_base_launch']),all(rule('base_depth_pct','<=','30'))],[{id:'score',desc:true},{id:'base_depth_pct',desc:false}],{base_quality_score:true,base_depth_pct:true,sma_compression_pct:true,dryup_after_accumulation:true}),
  screen('Early Trend / RWB — Strict',[any('trade_status',['entry_ready','trigger_pending']),all(rule('entry_risk_pct','<=','10'),rule('distance_to_trigger_pct','between','-5,1.5'),rule('rs_rating','>=','80'),rule('weekly_30w_slope_pct','>=','0')),group('ANY',[...['rwb_squeeze_thrust','guppy','ema_stack_launch','ema_cross','long_base_launch'].map(value=>rule('primary_setup','=',value)),...['thrusting','trendline_breakout','confirmed'].map(value=>rule('rwb_squeeze_phase','=',value)),...['early_ignition','stack_thrust','follow_through'].map(value=>rule('ema_stack_phase','=',value))])],[{id:'score',desc:true},{id:'distance_to_trigger_pct',desc:true}],{trade_status:true,entry_risk_pct:true,distance_to_trigger_pct:true,weekly_30w_slope_pct:true,rwb_squeeze_phase:true,ema_stack_phase:true}),
  screen('Early Trend / RWB — Relaxed',[any('trade_status',['entry_ready','trigger_pending']),all(rule('entry_risk_pct','<=','10'),rule('distance_to_trigger_pct','between','-10,2.5'),rule('rs_rating','>=','70')),group('ANY',[...['rwb_squeeze_thrust','guppy','ema_stack_launch','ema_cross','long_base_launch'].map(value=>rule('primary_setup','=',value)),...['watch_squeeze','thrusting','trendline_breakout','confirmed'].map(value=>rule('rwb_squeeze_phase','=',value)),...['coil_watch','early_ignition','stack_thrust','follow_through'].map(value=>rule('ema_stack_phase','=',value))])],[{id:'score',desc:true},{id:'distance_to_trigger_pct',desc:true}],{trade_status:true,entry_risk_pct:true,distance_to_trigger_pct:true,rwb_squeeze_phase:true,ema_stack_phase:true}),
  screen('RS Leaders Near High',[all(rule('rs_rating','>=','90'),rule('distance_to_52w_high_pct','>=','-12'))],[{id:'rs_rating',desc:true},{id:'distance_to_52w_high_pct',desc:true}],{rs_score_weighted:true,rs_line_at_52w_high:true,rs_new_high_before_price:true,mansfield_rs:true}),
  screen('Launch/Volume',[group('ANY',[...['ema_stack_launch','rwb_squeeze_thrust','long_base_launch'].map(value=>rule('primary_setup','=',value)),...['early_ignition','stack_thrust','follow_through'].map(value=>rule('ema_stack_phase','=',value)),...['thrusting','trendline_breakout','confirmed'].map(value=>rule('rwb_squeeze_phase','=',value))])],[{id:'focusBlend',desc:true},{id:'avg_dollar_volume_50d',desc:true}],{ema_stack_launch_score:true,ema_stack_phase:true,rwb_squeeze_score:true,rwb_squeeze_phase:true,demand_supply_ratio:true}),
  screen('Accumulation Watch',[group('ANY',[rule('accumulation_score','>=','55'),rule('institutional_footprint_score','>=','55'),rule('long_base_score','>=','50')])],[{id:'accumulation_score',desc:true},{id:'rs_rating',desc:true}],{accumulation_score:true,institutional_footprint_score:true,base_quality_score:true,support_volume_events:true,up_down_vol_ratio_50d:true}),
  screen('Stage 1 → 2 Recovery',[all(rule('weinstein_stage','=','1'),rule('weinstein_substage','=','1C_pre_breakout'),rule('weinstein_stage_origin','=','from_decline'),rule('long_term_context','=','secular_recovery'),rule('secular_recovery_score','>=','55'))],[{id:'secular_recovery_score',desc:true},{id:'focusBlend',desc:true}],{secular_recovery_score:true,weinstein_substage:true,weinstein_ext_pct:true,weinstein_resistance_zone_high:true,weinstein_support_zone_low:true,long_term_drawdown_pct:true,mansfield_rs:true}),
  screen('Minervini — Trend Template',[all(rule('primary_setup','=','minervini'),rule('rs_rating','>=','70'),rule('distance_to_52w_high_pct','>=','-25'))],[{id:'rs_rating',desc:true},{id:'score',desc:true}],{rs_score_weighted:true,base_quality_score:true,weinstein_stage:true,weinstein_ext_pct:true}),
  screen('Minervini — VCP',[all(rule('rs_rating','>=','80'),rule('distance_to_52w_high_pct','>=','-15'),rule('base_quality_score','>=','60'))],[{id:'base_quality_score',desc:true},{id:'base_depth_pct',desc:false}],{base_quality_score:true,base_depth_pct:true,sma_compression_pct:true,dryup_after_accumulation:true}),
  screen('Weinstein — Stage 2 Breakout',[all(rule('weinstein_stage','=','2'),rule('mansfield_rs','>','0'),rule('weekly_breakout_rvol','>=','1.4'),rule('weinstein_ext_pct','<=','15')),any('weinstein_substage',['2A_fresh_breakout','2B_healthy_advance'])],[{id:'rs_rating',desc:true},{id:'weinstein_ext_pct',desc:false}],{weinstein_stage:true,weinstein_substage:true,weinstein_ext_pct:true,mansfield_rs:true,weinstein_stage_quality_score:true}),
  screen('Stamatoudis — 10/20 EMA Momentum',[any('primary_setup',['ema_cross','tight_breakout']),all(rule('rs_score_3m','>','0'),rule('avg_dollar_volume_50d','>=','5000000'))],[{id:'rs_rating',desc:true},{id:'rs_score_3m',desc:true}],{rs_score_3m:true,base_depth_pct:true,up_down_vol_ratio_50d:true}),
  screen('Qullamaggie — Momentum',[all(rule('rs_rating','>=','90'),rule('distance_to_52w_high_pct','>=','-25'),rule('avg_dollar_volume_50d','>=','10000000'),rule('adr_pct','between','4,20'),rule('ret_3m_pct','>=','30')),group('ANY',[...['tight_breakout','glb','high_rs','ema_cross'].map(value=>rule('primary_setup','=',value)),rule('pocket_pivot','true')])],[{id:'rs_rating',desc:true},{id:'ret_3m_pct',desc:true}],{adr_pct:true,ret_3m_pct:true,rs_score_weighted:true,base_depth_pct:true}),
  screen('Oliver Kell — Reclaim / Launch',[all(rule('rs_rating','>=','85')),group('ANY',[rule('primary_setup','=','ema_cross'),...['early_ignition','stack_thrust','follow_through'].map(value=>rule('ema_stack_phase','=',value)),rule('long_base_phase','=','launching'),...['thrusting','confirmed'].map(value=>rule('rwb_squeeze_phase','=',value))])],[{id:'focusBlend',desc:true},{id:'rs_rating',desc:true}],{rs_turning_up:true,accumulation_score:true}),
  screen('Oliver Kell — 52W Highs',[all(rule('distance_to_52w_high_pct','>=','-5'),rule('rs_line_at_52w_high','true'),rule('rs_rating','>=','85'))],[{id:'rs_rating',desc:true},{id:'distance_to_52w_high_pct',desc:true}],{rs_line_at_52w_high:true,rs_new_high_before_price:true,rs_score_weighted:true}),
  screen('Oliver Kell — Bull Snort',[all(rule('rs_rating','>=','80')),group('ANY',[rule('weekly_breakout_rvol','>=','2'),rule('daily_rvol_headsup','true'),rule('pocket_pivot','true')])],[{id:'rs_rating',desc:true},{id:'volume_ratio_50d',desc:true}],{up_down_vol_ratio_50d:true,volume_ratio_50d:true,pocket_pivot:true}),
  screen("O'Neil — CAN SLIM Leaders",[any('primary_setup',['high_rs','minervini']),all(rule('rs_rating','>=','85'),rule('rs_line_at_52w_high','true'),rule('distance_to_52w_high_pct','>=','-15'))],[{id:'rs_rating',desc:true},{id:'score',desc:true}],{rs_line_at_52w_high:true,rs_score_weighted:true,base_quality_score:true}),
  screen('Pocket Pivot (Morales/Kacher)',[all(rule('pocket_pivot','true'),rule('rs_rating','>=','70'),rule('up_down_vol_ratio_50d','>=','1'))],[{id:'rs_rating',desc:true},{id:'up_down_vol_ratio_50d',desc:true}],{pocket_pivot:true,up_down_vol_ratio_50d:true,volume_ratio_50d:true}),
  screen('Qullamaggie — Episodic Pivot',[all(rule('ret_1d_pct','>=','7.5'),rule('rvol_today','>=','3'),rule('avg_dollar_volume_50d','>=','20000000'))],[{id:'ret_1d_pct',desc:true},{id:'rvol_today',desc:true}],{ret_1d_pct:true,rvol_today:true,adr_pct:true}),
  screen('Oliver Kell — Doublers',[all(rule('ret_6m_pct','>=','100'),rule('rs_rating','>=','90'))],[{id:'ret_6m_pct',desc:true},{id:'rs_rating',desc:true}],{ret_6m_pct:true,ret_3m_pct:true,adr_pct:true}),
]

export const bottomRecipeTabs=[
  {label:'All',value:'All'},{label:'Accumulation',value:'accumulation_base'},{label:'Crash Base',value:'crash_base_stage1'},
  {label:'RWB',value:'rwb_squeeze_thrust'},{label:'EMA Stack',value:'ema_stack_launch'},{label:'MA Cluster',value:'ma_cluster_volume_breakout'},
  {label:'Long Base',value:'long_base_launch'},{label:'Stage / Weinstein',value:'weinstein'},{label:'Tight / VCP',value:'tight_breakout'},
]as const

export const bottomCoreColumns=new Set(['watch','ticker','focusBlend','tradeStatus','triggerState','entryRiskPct','actionability','primarySetup','stage','rsRank','baseScore','volumeRatio','distanceToTrigger'])
