import{useMemo,useState}from'react'
import{buildIndicatorSeries,isUpsloping,normalizedSlope,type IndicatorBar}from'../../../supabase/functions/_shared/indicatorSignals.ts'
import{useOwnerData}from'./OwnerDataProvider'
import type{IndicatorConfirmation,IndicatorDirection,IndicatorSignal,OwnerIndicatorAlertPayloadV1}from'./alerts'
import'./indicatorAlert.css'

type Bar={time:string;close:number}
type Props={ticker:string;bars:Bar[];onCancel:()=>void;onSaved:()=>void}

const latest=(values:Array<number|null>)=>{for(let index=values.length-1;index>=0;index-=1)if(values[index]!==null)return values[index] as number;return null}
const signalLabel=(signal:IndicatorSignal)=>signal==='daily_ema_10_20'?'10/20 EMA · Daily':'10/20 SMA · Weekly'
const conditionLabel=(condition:IndicatorConfirmation)=>condition==='sma50_daily_up'?'50D SMA is upsloping':'30W SMA is upsloping'

export default function IndicatorAlertDialog({ticker,bars,onCancel,onSaved}:Props){
  const owner=useOwnerData(),[signal,setSignal]=useState<IndicatorSignal>('daily_ema_10_20'),[direction,setDirection]=useState<IndicatorDirection>('up'),[conditions,setConditions]=useState<IndicatorConfirmation[]>([]),[mode,setMode]=useState<'all'|'any'>('all'),[busy,setBusy]=useState(false),[message,setMessage]=useState('')
  const series=useMemo(()=>buildIndicatorSeries(bars.map(bar=>({time:bar.time,close:bar.close})as IndicatorBar)),[bars])
  const daily50=series.daily.sma50.filter((value):value is number=>value!==null),weekly30=series.weekly.sma30.filter((value):value is number=>value!==null)
  const preview=signal==='daily_ema_10_20'?{fast:latest(series.daily.ema10),slow:latest(series.daily.ema20),interval:'daily',bar:series.daily.bars.at(-1)?.time??'—'}:{fast:latest(series.weekly.sma10),slow:latest(series.weekly.sma20),interval:'weekly',bar:series.weekly.bars.at(-1)?.time??'—'}
  const toggle=(condition:IndicatorConfirmation)=>setConditions(current=>current.includes(condition)?current.filter(value=>value!==condition):[...current,condition])
  const submit=async(event:React.FormEvent)=>{event.preventDefault();setBusy(true);setMessage('');const payload:OwnerIndicatorAlertPayloadV1={version:1,kind:'indicator',signal,direction,confirmations:{mode,conditions},evaluationInterval:signal==='weekly_sma_10_20'?'weekly':'daily',rearm:'after_clear'};try{await owner.saveAlert({name:`${ticker} ${signalLabel(signal)} ${direction==='either'?'cross':`${direction} cross`}`,ticker,enabled:true,payload});setMessage('Indicator alert synced for the next verified EOD run.');onSaved()}catch(error){setMessage(error instanceof Error?error.message:String(error))}finally{setBusy(false)}}
  return<div className="chart-dialog-backdrop"><form className="chart-dialog indicator-alert-dialog" role="dialog" aria-modal="true" aria-labelledby="indicator-alert-title" onSubmit={submit}><b id="indicator-alert-title">Indicator alert</b><p>Owner-only alert evaluated after the next verified {signal==='weekly_sma_10_20'?'completed weekly':'daily'} EOD bar. It fires once per cross and rearms after the condition clears.</p><label>Signal<select autoFocus value={signal} onChange={event=>setSignal(event.target.value as IndicatorSignal)}><option value="daily_ema_10_20">10/20 EMA cross · Daily</option><option value="weekly_sma_10_20">10/20 SMA cross · Weekly</option></select></label><label>Direction<select value={direction} onChange={event=>setDirection(event.target.value as IndicatorDirection)}><option value="up">Cross up</option><option value="down">Cross down</option><option value="either">Either direction</option></select></label><fieldset><legend>Optional confirmations</legend>{(['sma50_daily_up','sma30_weekly_up']as IndicatorConfirmation[]).map(condition=><label className="owner-checkbox" key={condition}><input type="checkbox" checked={conditions.includes(condition)} onChange={()=>toggle(condition)}/>{conditionLabel(condition)}</label>)}{conditions.length>1?<label>Combine confirmations<select value={mode} onChange={event=>setMode(event.target.value as'all'|'any')}><option value="all">All selected (recommended)</option><option value="any">Any selected</option></select></label>:null}</fieldset><div className="indicator-alert-preview"><b>Current chart context</b><span>{ticker} · {signalLabel(signal)} · last {preview.bar}</span><span>Fast {preview.fast===null?'—':preview.fast.toFixed(2)} · Slow {preview.slow===null?'—':preview.slow.toFixed(2)}</span><span>50D slope {normalizedSlope(daily50,20)===null?'Needs history':isUpsloping(daily50,20)?'Upsloping':'Not upsloping'} · 30W slope {normalizedSlope(weekly30,8)===null?'Needs history':isUpsloping(weekly30,8)?'Upsloping':'Not upsloping'}</span></div>{message?<p className="chart-drawing-message" role={/synced/i.test(message)?'status':'alert'}>{message}</p>:null}<div><button type="button" onClick={onCancel} disabled={busy}>Cancel</button><button type="submit" className="chart-primary-alert" disabled={busy}>{busy?'Saving…':'Save & arm'}</button></div></form></div>
}
